### ISSUE TITLE
Confirm that external call reverts in `checkConditions` and `checkHatWearerStanding` behave as expected

### ISSUE THREAD

**Issue by slgraham** [Hats-Protocol/hats-protocol#20]

**Comment by slgraham** [comment]
Looks like this actually doesn't work with try/catch -- when attempting to call these functions on an address that is not a contract, the call failure isn't caught. Still not sure exactly why this is the case.

One possible option is to ensure that the address we are calling the function on is a contract, eg by checking that the address is a contract a la [openzeppelin address.sol](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/5fbf494511fd522b931f7f92e2df87d671ea8b0b/contracts/utils/Address.sol#L36-L42)

**Comment by nintynick** [comment]
resolved with https://github.com/Hats-Protocol/hats-protocol/pull/34/commits/fa174f1f0aa83cbd80ef4718a1cccfcbd8413d48
